---
- name: download vim repository
  git:
    repo: https://github.com/vim/vim.git
    dest: /usr/src/vim

- name: install vim
  command: "{{ item }}"
  args:
    chdir: /usr/src/vim
  with_items:
    - make
    - make install

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
    dest: ~/.vim/autoload/plug.vim

- name: generate .vimrc with plugins
  template: src=.vimrc.j2 dest=~/.vimrc
