---
- name: download vim repository
  git:
    repo: https://github.com/vim/vim.git
    dest: /usr/src/vim

- name: check vim install status
  command: /usr/local/bin/vim --version
  register: vim_status
  changed_when: False
  ignore_errors: True

- name: install vim
  make:
    chdir: /usr/src/vim
    target: install
  when: vim_status.failed

- name: create directory for vim-plug
  file:
    path: ~/.vim/autoload
    state: directory

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: generate .vimrc with plugins
  template: src=.vimrc.j2 dest=~/.vimrc
